### PR TITLE
Vade updates

### PR DESCRIPTION
**Pull request by vade**
Hey @bangnoise - some small tweaks to support MRT rendering in v002 FBO, and a simple addition to master plugin interface to remind idiots like me to call super :) 

Hazily created for some work on an updated Kinect plugin where MRT is needed, so let me know if this seems dumb.

### CODE REVIEW

**Comment by bangnoise** [comment]
Your could block for the shader could pass self as an argument when it's called rather than having plugins have to weak ref self when they create it

Otherwise LGTM - reviewed in browser, haven't tested

**Comment by vade** [comment]
Yea I saw that technique posted the other day, you pass the QCPlugin instance in. Ill make it do that tomorrow perhaps!

**Comment by vade** [comment]
Hey let me know if this is to your liking. I do prefer it myself. Thanks for the impetus. I am thinking of extending v002 Master Plugin Interface to provide some generic 3D support (translation, rotation, scaling) and possibly some render mode support like blend mode,  switching from Model / Wireframe / Point + point sprite support, etc, objects we make can inherit functionality from one place.

Thoughts?

**Comment by vade** [comment]
Oh and of course, path handling - since thats always more of a pain in the ass than it should be, ha.

**Comment by bangnoise** [comment]
LGTM by in-browser review, merge away.

Re grander plans - KISS but if every instance of this class is going to require all those features then sure

**Comment by vade** [comment]
Yea, I hear you. I was thinking of maybe making categories and optional headers to include. Like MasterPluginInterface (OpenGLBlending), MasterPluginInterface (PathTools), MasterPluginInterface(OpenGL3DTransforms) etc.

**Pull request merged**
